### ISSUE TITLE
reportportal.io doesn't reflect all integrations and it's very hard to navigate through test frameworks integration 

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal-website#18]
see topic

It seems java based stuff is officially supported, nothing more...

**Comment by DzmitryHumianiuk** [comment]
working with it.

will create a table of supported platforms, based on clients

**Comment by evjlobanova** [comment]
@nvborisenko we`ve made a section with description on reportportal.io - http://reportportal.io/download

**Comment by nvborisenko** [comment]
Thanks, much better.
