### ISSUE TITLE
Add Reqnroll test framework

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal-website#471]
Hi Team,

On the https://reportportal.io/installation page we need to add new supported test framework for:
- Tab: .NET
- Our github repo: https://github.com/reportportal/agent-dotnet-reqnroll
- Their web site: https://reqnroll.net/
- Image like this: 
![image](https://github.com/reportportal/reportportal.github.io/assets/22616990/bcc18e14-438f-480c-a221-71c639338359)

I could propose a PR, but I don't now how to make the SVG image.

**Comment by AmsterGet** [comment]
Hi @nvborisenko !
Thanks for highlighting this!
I'll ask our UI team to update the page.
We are also going to add a Vitest integration mention, so it will be bulk update.

**Comment by AmsterGet** [comment]
Also, is it okay to announce it on RP's social media channels?
cc @VeranikaRymzha

**Comment by nvborisenko** [comment]
Thanks.
